---
spring:
  application:
    name: "gateway-service"
server:
  port: 8800
service:
  version: "0.0.2-SNAPSHOT"
  name: "${spring.application.name}"
  port: "${server.port}"
management:
  endpoints:
    web:
      exposure:
        include: "*"
